#!/bin/bash

function init_influxdb(){
  influxd run --bolt-path /data/influxd.bolt --engine-path /data/engine --store bolt &
  pid=$!
  while true
  do
    sleep 2
    has_bucket=$(influx bucket ls  | awk '$2==ENVIRON["INFLUXDB_BUCKET"] {print $2}')
    if [ "$has_bucket" ]; then
      break
    else
      echo "Initializing influxdb..."
      influx setup -f -o "${INFLUXDB_ORG}" \
        -b "${INFLUXDB_BUCKET}" \
        -u "${INFLUXDB_USER}" \
        -p "${INFLUXDB_PASSWORD}" \
        -t "${INFLUXDB_TOKEN}" \
        -r "${INFLUXDB_RETENTION}" \
        > /dev/null 2>&1
    fi
  done
  kill -15 $pid && wait $pid
}

init_influxdb
exec influxd run --bolt-path /data/influxd.bolt --engine-path /data/engine --store bolt
