#!/bin/bash

function setup_influxdb(){
  influx setup -f -o "${INFLUXDB_ORG}" \
    -b "${INFLUXDB_BUCKET}" \
    -u "${INFLUXDB_USER}" \
    -p "${INFLUXDB_PASSWORD}" \
    -t "${INFLUXDB_TOKEN}" \
    > /dev/null 2>&1
}

function pre_influxdb(){
  influxd &
  pid=$!
  while true
  do
    sleep 2
    if setup_influxdb; then
      touch /root/.influxdbv2/setup_handled
      break
    elif [ -e /root/.influxdbv2/setup_handled ]; then
      break
    else
      echo "Waiting influxdb start..."
    fi
  done
  kill -15 $pid && wait $pid
}

pre_influxdb
exec influxd
