image_org: "drycc"
image_pull_policy: "Always"
image_tag: "canary"
image_registry: "docker.io"
# limits_cpu: "100m"
# limits_memory: "50Mi"
# Configure the following ONLY if using an off-cluster Influx v2 database
# URL configuration is only available in off-cluster Influx database
url: "http://my.influx.url:8086"
bucket: "kubernetes"
org: "drycc"
# If it is off-cluster, it must be specified
# Otherwise, it is generated randomly, if it is empty
token: ""
# Configure the following is only available in on-cluster Influx database
user: "admin"
password: "admin123"
retention: "30d"

# Any custom environment variables
# can be specified as key-value pairs under environment
# this is usually a non required setting.
environment:
  RESERVED_NAMES: "drycc-influxdb"

# GCP PDs and EBS volumes are supported only
persistence:
  enabled: false # Set to true to enable persistence
  accessMode: ReadWriteOnce
  size: 5Gi # PVC size
  ## influxdb data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  ## Storage class of PV to bind. By default it looks for standard storage class.
  ## If the PV uses a different storage class, specify that here.
  storageClass: ""
  volumeName: ""

global:
  # Set the location of Workflow's influxdb cluster
  #
  # Valid values are:
  # - on-cluster: Run Influxdb within the Kubernetes cluster
  # - off-cluster: Influxdb is running outside of the cluster and credentials and connection information will be provided.
  influxdb_location: "on-cluster"
  # Role-Based Access Control for Kubernetes >= 1.5
  use_rbac: false
  ingress_class: ""
  # A domain name consists of one or more parts.
  # Periods (.) are used to separate these parts.
  # Each part must be 1 to 63 characters in length and can contain lowercase letters, digits, and hyphens (-).
  # It must start and end with a lowercase letter or digit.
  cluster_domain: "cluster.local"
  # The public resolvable hostname to build your cluster with.
  #
  # This will be the hostname that is used to build endpoints such as "drycc.$HOSTNAME"
  platform_domain: ""
  # Whether cert_manager is enabled to automatically generate drycc certificates
  cert_manager_enabled: true
