apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "drycc-influxdb"
  labels:
    app: "drycc-influxdb"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/tls-acme: "true"
    {{- if not (eq .Values.global.ingress_class "") }}
    kubernetes.io/ingress.class: "{{ .Values.global.ingress_class }}"
    {{ end }}
spec:
  rules:
  - host: drycc-influxdb.{{ .Values.global.platform_domain }}
    http:
      paths:
      {{- if eq .Values.global.ingress_class "gce" "alb" }}
      - path: /*
      {{- else }}{{/* Has annotations but ingress class is not "gce" nor "alb" */}}
      - path: /
      {{- end }}
        backend:
          serviceName: drycc-influxdb
          servicePort: 80
  {{ if .Values.global.cert_manager_enabled }}
  tls:
    - secretName: drycc-influxdb-auto-tls
      hosts:
        - drycc-influxdb.{{ .Values.global.platform_domain }}
  {{- end }}
