{{- if eq .Values.global.influxdbLocation "on-cluster" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drycc-influxdb
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: drycc-influxdb
  selector:
    matchLabels:
      app: drycc-influxdb
  template:
    metadata:
      labels:
        app: drycc-influxdb
    spec:
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset.type "key" .Values.podAffinityPreset.key "values" .Values.podAffinityPreset.values ) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset.type "key" .Values.podAntiAffinityPreset.key "values" .Values.podAntiAffinityPreset.values ) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values ) | nindent 10 }}
      containers:
      - name: drycc-influxdb-proxy
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/influxdb:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
          - start-proxy.py
        {{- if or (.Values.limitsCpu) (.Values.limitsMemory)}}
        resources:
          limits:
            {{- if (.Values.limitsCpu) }}
            cpu: {{.Values.limitsCpu}}
            {{- end}}
            {{- if (.Values.limitsMemory) }}
            memory: {{.Values.limitsMemory}}
            {{- end}}
        {{- end}}
        ports:
        - containerPort: 8000
          name: proxy
          protocol: TCP
        env:
        {{- $backends := (list ) }}
        {{ $backendCount := .Values.replicas | int }}
        {{- range $i := until $backendCount }}
        {{- $backends = (append $backends (printf "http://drycc-influxdb-%d.drycc-influxdb.%s.svc.%s:8086" $i $.Release.Namespace $.Values.global.clusterDomain)) }}
        {{- end -}}
        - name: "RELAY_BACKENDS"
          value: {{ join "," $backends }}
        - name: "RELAY_BACKENDS_INTERVAL"
          value: "172800"
        - name: "RELAY_BACKENDS_BLOCK_TIME"
          value: "60"
        livenessProbe:
          httpGet:
            path: /health
            port: http
      - name: drycc-influxdb-backend
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/influxdb:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
          - start-backend.sh
        {{- if or (.Values.limitsCpu) (.Values.limitsMemory)}}
        resources:
          limits:
            {{- if (.Values.limitsCpu) }}
            cpu: {{.Values.limitsCpu}}
            {{- end}}
            {{- if (.Values.limitsMemory) }}
            memory: {{.Values.limitsMemory}}
            {{- end}}
        {{- end}}
        ports:
        - containerPort: 8086
          name: backend
          protocol: TCP
        env:
        - name: "INFLUXDB_BUCKET"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: bucket
        - name: "INFLUXDB_ORG"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: org
        - name: "INFLUXDB_USER"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: user
        - name: "INFLUXDB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: password
        - name: "INFLUXDB_TOKEN"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: token
        - name: "INFLUXDB_RETENTION"
          value: {{.Values.retention}}
        {{- range $key, $value := .Values.environment }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
{{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: influxdb-data
          mountPath: /data
      # Allow user influxdb to write to /data
      securityContext:                
        fsGroup: 1001         
        runAsGroup: 1001     
        runAsUser: 1001
      volumes:
      - name: influxdb-data
        persistentVolumeClaim:
          claimName: drycc-influxdb
{{- end }}
{{- end }}
