{{- if eq .Values.global.influxdbLocation "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-influxdb
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
    app: drycc-influxdb
spec:
  ports:
  - port: 80
    name: proxy
    targetPort: proxy
  - port: 8086
    name: backend
    targetPort: backend
  selector:
    app: drycc-influxdb
{{- end }}
