{{- if eq .Values.global.influxdb_location "off-cluster" }}
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-creds
  labels:
    heritage: drycc
type: Opaque
data:
  url: {{ .Values.influxdb.url | b64enc }}
  database: {{ .Values.influxdb.database | b64enc }}
  username: {{ .Values.influxdb.username | b64enc }}
  password: {{ .Values.influxdb.password | b64enc }}
{{- end }}
