{{- if eq .Values.global.influxdbLocation "on-cluster" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-influxdb
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: drycc-influxdb
  template:
    metadata:
      labels:
        app: drycc-influxdb
    spec:
      {{- if .Values.global.common }}
      {{- include "common.affinity" (dict "key" "app" "values" (list "drycc-influxdb")) | indent 6 }}
      {{- end }}
      containers:
      - name: drycc-influxdb
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/influxdb:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
{{- if or (.Values.limitsCpu) (.Values.limitsMemory)}}
        resources:
          limits:
{{- if (.Values.limitsCpu) }}
            cpu: {{.Values.limitsCpu}}
{{- end}}
{{- if (.Values.limitsMemory) }}
            memory: {{.Values.limitsMemory}}
{{- end}}
{{- end}}
        ports:
        - containerPort: 8086
          name: transport
          protocol: TCP
        env:
        - name: "INFLUXDB_BUCKET"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: bucket
        - name: "INFLUXDB_ORG"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: org
        - name: "INFLUXDB_USER"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: user
        - name: "INFLUXDB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: password
        - name: "INFLUXDB_TOKEN"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: token
        - name: "INFLUXDB_RETENTION"
          value: {{.Values.retention}}
{{- range $key, $value := .Values.environment }}
        - name: {{ $key }}
          value: {{ $value | quote }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
{{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: influxdb-data
          mountPath: /data
      # Allow user influxdb to write to /data
      securityContext:
        fsGroup: 1001
      volumes:
      - name: influxdb-data
        persistentVolumeClaim:
          claimName: drycc-influxdb
{{- end }}
{{- end }}
