{{- if eq .Values.global.influxdb_location "on-cluster" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-influxdb
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.image_tag }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: drycc-influxdb
  template:
    metadata:
      labels:
        app: drycc-influxdb
    spec:
      containers:
      - name: drycc-influxdb
        image: {{.Values.image_registry}}{{.Values.org}}/influxdb:{{.Values.image_tag}}
        imagePullPolicy: {{.Values.image_pull_policy}}
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
        resources:
          limits:
{{- if (.Values.limits_cpu) }}
            cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
            memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
        ports:
        - containerPort: 8086
          name: transport
          protocol: TCP
        env:
        - name: "INFLUXDB_BUCKET"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: bucket
        - name: "INFLUXDB_ORG"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: org
        - name: "INFLUXDB_USER"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: user
        - name: "INFLUXDB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: password
        - name: "INFLUXDB_TOKEN"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: token
        - name: "INFLUXDB_RETENTION"
          value: {{.Values.retention}}
{{- range $key, $value := .Values.environment }}
        - name: {{ $key }}
          value: {{ $value | quote }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
{{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: influxdb-data
          mountPath: /data
      # Allow user influxdb to write to /data
      securityContext:
        fsGroup: 1001
      volumes:
      - name: influxdb-data
        persistentVolumeClaim:
          claimName: drycc-influxdb
{{- end }}
{{- end }}
