apiVersion: v1
kind: Secret
metadata:
  name: influxdb-creds
  labels:
    heritage: drycc
type: Opaque
data:
  url: {{ .Values.url | b64enc }}
  bucket: {{ .Values.bucket | b64enc }}
  org: {{ .Values.org | b64enc }}
  user: {{ .Values.user | b64enc }}
  {{- if .Values.token }}
  token: {{ .Values.token  | b64enc | quote }}
  {{- else }}
  token: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.password }}
  password: {{ .Values.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
