apiVersion: v1
kind: Secret
metadata:
  name: influxdb-creds
  labels:
    heritage: drycc
type: Opaque
data:
  {{- if eq .Values.global.influxdbLocation "off-cluster" }}
  url: {{ .Values.url | b64enc }}
  {{- else }}
  user: {{ .Values.user | b64enc }}
  password: {{ .Values.password | b64enc }}
  {{- end}}
  bucket: {{ .Values.bucket | b64enc }}
  org: {{ .Values.org | b64enc }}
  token: {{ default (randAlphaNum 32 | b64enc) (.Values.token | b64enc) }}
