matrix:
  platform:
  - linux/amd64
  - linux/arm64

platform: ${platform}

labels:
  type: exec

pipeline:
- name: test-linux
  image: bash
  commands:
  - make docker-build test
  secrets:
  - dev_registry
  when:
    event:
    - push
    - tag
    - pull_request
